### PR TITLE
Donation process using Clubhouse story template

### PR DESCRIPTION
**Pull request by victorwuky**

### CODE REVIEW

**Comment by victorwuky** [comment]
@nicks : Can you please review? (Also pay attention to the tasks in the Clubhouse story template, in particular approval flow and expenses).

**Comment by victorwuky** [comment]
> By the time there's a designated DD with a candidate organization, the donation generally gets done--I don't think that adding the overhead of a clubhouse ticket at that step would be useful. Just my two cents.

@maiamcc : I don't doubt we are good at getting people to find an organization and donating. 

> Fwiw, this seems like overkill to me. What problem are you trying to solve?

I want to streamline an existing process so that organizationally we get good at getting things done and be generally efficient. I think having a process and Clubhouse story template helps makes this async achieves this goal. However, this may seem very cold and too robotic for a task that is specifically supposed to help humans. If that's your concern, more than happy to close this PR (and delete the template in Clubhouse).

**Comment by victorwuky** [comment]
Closing this since at least one negative signal from Maia, and streamlining this process is not high priority for me.

**Comment by maiamcc** [comment]
Whoops sorry, I got distracted. I figured out what feels weird about this! The breakdown in the donation deputy process currently is the donation deputy doing the thing, so I feel weird about putting extra process on the DD to do the thing.

However, something that might HELP is that, when we assign a DD, we (so, whoever assigns DDs--probably @nicks in practice) create a "make a donation" ticket an assign it to them--that way, this bit of work persists in their docket.

I don't have strong feelings about the review process, it's seemed fine thus far to do it in planning and I've liked getting group consent for the organization, though I suppose that could be moved to "tag a single person in your clubhouse ticket, they approve/reject the proposed org."

what do you think @victorwuky ? if this seems reasonable, I can write it up.

**Comment by victorwuky** [comment]
@maiamcc : I don't have strong opinions either. Just spent a bit of my brain juice to think about it this month since I'm DD. So if you want to write something up in a new PR, I'd gladly review it.

**Pull request closed without merging**
