### PR TITLE
Exterminator (bug triage) process changes and prioritizing small improvements changes

### PR DESCRIPTION
**Pull request by victorwuky**
## Exterminator (bug triage) problem
- We are seeing an increase in bugs reported. (Please correct me (Victor) if I'm wrong.) Over time, we will have even more bugs as we get more users and the surface area of the product increases.
- We need a more scalable way to manage the amount and fixing of bugs.
- I (Victor) think we currently are over-reporting bugs (see https://github.com/windmilleng/company/pull/3). But nonetheless, we can address that concern separately.
- Currently, we are relying on a single individual (see [doc](https://docs.google.com/document/d/10O95DVggY-0Z8Vu17AhHMv4FM1ORJRPyoivNLj-ybyE/edit#)) as a process to triage and fix bugs, and possibly assign them to teams to work on.

## Prioritizing small improvements problem
- Currently we have [a process](https://github.com/windmilleng/company/tree/master/teams) to have individual teams work on individual projects. But this means there's isn't a straightforward way to prioritize small improvement changes, because they often don't fit into a bigger category. Consequently, one team starting 2020 Feb 24 to end of Mar is now working on a collection of small fixes, instead of one large business-focused initiative. 
- This isn't a great arrangement since we want teams to be empowered to solve big meaty business problems, giving them space and time to do so. But at the same time, we also need continual maintenance of Tilt with small improvements.

## Proposal
- The exterminator on rotation should set a higher bar for bugs that need to be fixed immediately. (In particular, we may consider a sev model (Sev1, Sev2, etc.) and a corresponding target SLA definition. This can be a separate process change / PR.) This way, the exterminator can focus on bug triage (and less on bug fixes), as well as other assigned tasks, so that hopefully they still have time to participate in team activities.
- Instead of having continual 6 week sprints, with no break in between, introduce a 2 week "cool-down" period.
- During this cool down period, teams work on:
  - Smaller improvements that users have asked for, but that don't belong to a big bucket of work.
  - Bug fixes.
  - Preparing for the next sprint.
- So the schedule would be:
  - 6 week sprint
  - 2 week cool down
  - 6 week sprint
  - 2 week cool down
  - ...

## Resources
- The concept of a cool-down period is mentioned here: https://basecamp.com/shapeup/2.2-chapter-08#cool-down. This is from a recent book by Ryan Singer, Head of Strategy at Basecamp.
- Here's another section addressing bugs: https://basecamp.com/shapeup/2.2-chapter-08#what-about-bugs
- Slite calls this a regroup week(s): https://startupbibles.slite.com/p/channel/NeJx8ARPYFj7gLHnkppJHk

### CODE REVIEW

**Comment by victorwuky** [comment]
@maiamcc @jazzdan: Thank you both for bringing up the problems I think I've written up in the description here. Please do take a look and let me know if I haven't captured everything on your minds. 

I've also included a concrete proposal. Please do comment.

**Comment by maiamcc** [comment]
> Instead of having continual 6 week sprints, with no break in between, introduce a 2 week "cool-down" period.

I think it would be neat to try the "cooldown period" thing -- though a failure mode I foresee is that ppl take that cooldown to just keep polishing their team work from the last sprint (e.g. I know I had some spillover from last sprint that I'd totally finish up given another few days). I don't know if that's necessarily a _bad_ thing, but if everyone ends up using the cooldown as a continuation of the previous sprint, I'm not sure it's serving the intended purpose. That said, would love to try it.

> This way, the exterminator can focus on bug triage (and less on bug fixes), as well as other assigned tasks, so that hopefully they still have time to participate in team activities.

In my experience, the problem with exterminating vis a vis other other work is not the volume of work that I as an exterminator have to do, but rather the interruptions to my focus. I tend to enjoy fixing small/low-hanging/not-necessarily-serious bugs as an exterminator because it's a low-stakes way to fill an hour or two and I won't be upset if I'm pulled away by an incoming request, whereas trying to do project work and getting interrupted every 30-60 minutes is pretty frustrating. Not that it's impossible for exterminators to do feature work, but if we care about happening, IMO it's less about reducing the amount of time exterminators spend fixing bugs and more about reducing the amount of interrupt/number of channels to check.

**Comment by jazzdan** [comment]
## Quick aside about sprints

I personally don't care about sprint length. IMO sprints should be longer than 1 week, shorter than 1 quarter, and where you fall on that depends on the nature of the work you're doing.

What's important to me about sprints is that they have measurable results and a timeline. Then it's easy to see how much progress you've made at the halfway point and switch things up accordingly.

So I'd be down to try shorter sprints, I think that would make sense for the kind of work this team is doing right now. :)

## Severity/SLAs
We currently already have the SLA defined for the exterminator as:

> First response in an hour (during business time); updates to user until either solved or triaged out:
>Github - Tilt Issues
>Kubernetes Slack - #tilt channel
>Within a day:
>Email inbox (hi@windmill.engineering) (https://groups.google.com/a/windmill.engineering/forum/#!forum/hi)
DMs or Mentions to @windmill_eng
>All new users should be researched and entered into the CRM. If they’re a promising lead, the exterminator should reach out to them.

What do we think of this? Is this too demanding?

As for severity, we already have a severity definition in the GitHub issues, though it's just "Low" and "Hi". In my experience having more than three sev levels is overkill, and gets in to the Netflix star problem (people often categorize things as either critical, or not important, or somewhere in between and have trouble distinguishing within the in between bits).

I definitely think we could do with more agreed upon heuristics for determining if a bug is high/sev1, med/sev2 and low/sev3. Here's a strawperson proposal:

High: Tilt is broken for a critical use case, and there's no feasible short term workaround.
Medium: Tilt is broken for a critical use case, but there is a feasible short term workaround. Or Tilt is broken for a non-critical use case and there's no feasible short term workaround.
Low: Tilt is weird for this thing.

## Cool down period
I love it, I've also heard this called slack time. It has worked best for me when it was specifically allocated by management.

**Comment by victorwuky** [comment]
Thanks @maiamcc @jazzdan for the feedback.

Lots of problems and solutions here. I’m guessing the bug process seems to be smallest things to tweak if we want to? Maybe focus on that first?

> We currently already have the SLA defined for the exterminator as:

Matt: I read that section in the work agreement as the SLA for initial bug triage and not actual bug fix. I can understand how this part may be difficult since folks are essentially being user support every rotation, and by definition that’s a lot of interruptions, as Maia noted. 

I was hoping that we could tweak the bug priority / bug fix process. If we categorize bugs as H/M/L, could we add SLAs to each category, and thus bugs should automatically be spread out a bit in time? Eg if a M bug needs to be fixed within 3 weeks, then we assign it a due date of today + 3 weeks. And so it would just automatically flow into planning per that due date. And so I was hoping this would lighten some of the load of exterminator. But not sure if this solves any major problem currently?

**Comment by victorwuky** [comment]
Closing this PR and deleting the branch since we already have other PRs with specific proposals and ongoing updates to processes.

**Pull request closed without merging**
